name: Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        resource-group: 'aks-resource-group'
        cluster-name: 'my-aks-cluster'

    - name: Deploy to AKS
      run: |
        cd Terraform
        kubectl apply -f whoami-deployment.yaml
        kubectl apply -f canary-deployment.yaml

    - name: Verify deployment
      run: |
        kubectl get pods -l app=whoami-nodejs
        kubectl get pods -l app=whoami-canary
        kubectl get services
