name: Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        resource-group: 'my-aks-rg'
        cluster-name: 'dnmicroaks-aks'

    - name: Deploy to AKS
      run: |
        cd Terraform
        helm repo add flagger https://flagger.app
        helm repo update
        helm upgrade flagger flagger/flagger --namespace flagger-system --create-namespace --set meshProvider=nginx --set metricsServer=http://prometheus:9090
        kubectl apply -f whoami-deployment.yaml
        kubectl apply -f canary-deployment.yaml

    - name: Verify deployment
      run: |
        kubectl get pods -l app=whoami-nodejs
        kubectl get pods -l app=whoami-canary
        kubectl get services
